version: '3.8'

services:
    bd:
     image: postgres
     restart: always
     environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root
       POSTGRES_DB: pg
     ports:
       - 5432:5432
     volumes:
      - ./data:/var/lib/postgresql/data
